#!/usr/bin/env python3

import random

LIST_OF_NAME = [
    # From Strinova
    "michele",
    "nobunaga",
    "kokona",
    "yvette",
    "flavia",
    "yugiri",
    "leona",
    "chiyo",
    "lawine",
    "meredith",
    "reiichi",
    "kanami",
    "eika",
    "fragrans",
    "mara",
    "celestia",
    "audrey",
    "meddelena",
    "fuchsia",
    "galatea",
    "cielle",
    "lilith",
    # From Minecraft
    "alex",
    "steve",
    # From Phigros
    "gino",
    "geopelia",
    # From Honkai Star Rail & Honkai Impack 3rd
    "acheron",
    "aglaea",
    "anaxa",
    "archer",
    "argenti",
    "ashvell",
    "aventurine",
    "black_swan",
    "blade",
    "boothill",
    "bronya",
    "castorice",
    "cerydra",
    "cipher",
    "clara",
    "cyrene",
    "dr_ratio",
    "evanescia",
    "evernight",
    "firefly",
    "fugue",
    "gepard",
    "himeko",
    "hyacine",
    "hysilens",
    "jade",
    "kafka",
    "mortenax_blade",
    "mydei",
    "phainon",
    "rappa",
    "robin",
    "saber",
    "seele",
    "silver_wolf",
    "sparkie",
    "sparxie",
    "sunday",
    "the_dahlia",
    "the_herta",
    "topaz",
    "trailblazer",
    "tribble",
    "welt",
    "kiana",
    "elysia"
]

print(f"{random.choice(LIST_OF_NAME)}{str(random.randint(0, 2 ** 18))}")
