target("openminecraft-specs")
set_kind("static")
add_files("**.cpp")
add_packages("fmt", "zlib")
add_deps("openminecraft-log", "openminecraft-binary", "openminecraft-mem", "openminecraft-i18n")
add_includedirs("../../include")
