target("openminecraft-specs")
set_kind("static")
add_files("**.cpp")
add_packages("fmt", "zlib", "glm")
add_deps("openminecraft-log", "openminecraft-mem")
add_includedirs(path.join(os.projectdir(), "include"))
