#!/usr/bin/env python

import os
from multiprocessing import Process

sources = []

def recursive_listdir(path):
    for entry in os.listdir(path):
        full_path = os.path.join(path, entry)
        if os.path.isdir(full_path):
            recursive_listdir(full_path)
        else:
            sources.append(full_path)
recursive_listdir("./src")

def compile(s):
    print(f"Compiling {s} ...")
    os.system(f"javac -Xlint:-options --release 8 {s} -d out")

subpro = []
for s in sources:
    p = Process(target=compile,args=(s,))
    p.start()
    subpro.append(p)

for b in subpro:
    b.join()
    