#!/usr/bin/env python

import os

try:
    from tqdm.rich import tqdm
    TQDM_ENABLED = True
except BaseException as e:
    TQDM_ENABLED = False
import multiprocessing
import hashlib
import json
import warnings
warnings.filterwarnings('ignore')

def calculate_sha256(file_path):
    sha256 = hashlib.sha256()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b''):
            sha256.update(chunk)
    return sha256.hexdigest()

if os.path.exists("files.json"):
    hashes : dict = json.load(open("files.json", "r"))
else:
    hashes = {}

sources = []

def recursive_listdir(path):
    for entry in os.listdir(path):
        full_path = os.path.join(path, entry)
        if os.path.isdir(full_path):
            recursive_listdir(full_path)
        else:
            shares = calculate_sha256(full_path)
            if not full_path in hashes.keys() and hashes.keys() != shares:
                sources.append(full_path)
                hashes[full_path] = shares

recursive_listdir("./src")

def compile(s):
    print(f"Compiling {s} ...")
    ret = os.system(f"javac -Xlint:-options --release 8 {s} -cp src -d out")

    if not ret == 0:
        print(f"{s} compilation failed")
    
    return ret

if __name__ == '__main__':
    with multiprocessing.Pool(processes=__import__("multiprocessing").cpu_count()) as pool:
        if TQDM_ENABLED:
            results = list(tqdm(pool.imap(compile, sources), total=len(sources)))
        else:
            results = pool.map(compile, sources)

    json.dump(hashes, open("files.json", "w"))