target("openminecraft-renderer")
set_kind("static")
add_deps("openminecraft-fontproc")
add_packages("shaderc", "glm", "fmt", "boost", "vulkan-hpp", "libsdl3", "stb", "tinyobjloader")
add_files("**.cpp")
add_includedirs("../../include")
